---
.input-variables-mkdocs:
  - |
    echo -e "\n\033[1;34m💾 Print set inputs Variables\033[0m"
    printf "┌ %-30s ┬ %-100s ┐\n" "──────────────────────────────" "────────────────────────────────────────────────────────────────────────────────────────────────────"
    printf "| %-30s | %-100s |\n" "Variable" "Value"
    printf "├ %-30s ┼ %-100s ┤\n" "──────────────────────────────" "────────────────────────────────────────────────────────────────────────────────────────────────────"
    printf "| %-30s | %-100s |\n" "CONTAINER_IMAGE_PAGES" $CONTAINER_IMAGE_PAGES
    printf "└ %-30s ┴ %-100s ┘\n" "──────────────────────────────" "────────────────────────────────────────────────────────────────────────────────────────────────────"
