---
.input-variables-mkdocs:
  - |
    echo -e "\033[1;33m===>\033[0m 💾 Print set inputs Variables"
    echo -e "┌────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────┐"
    printf "| %-30s | %-100s |\n" "Variable" "Value"
    echo -e "├────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤"
    printf "| %-30s | %-100s |\n" "CONTAINER_IMAGE_PAGES" $CONTAINER_IMAGE_PAGES
    echo -e "└────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────┘"
